"""create entities

Revision ID: 3434c8aa02fe
Revises: 
Create Date: 2026-06-16 18:43:27.170106
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from src.infra.database.sqlalchemy import types as sqlalchemy_types


# revision identifiers, used by Alembic.
revision: str = '3434c8aa02fe'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.Column('city', sa.Text(), nullable=True),
    sa.Column('postal_code', sa.Text(), nullable=True),
    sa.Column('latitude', sa.REAL(), nullable=True),
    sa.Column('longitude', sa.REAL(), nullable=True),
    sa.Column('created_at', sqlalchemy_types.UTCDateTime(), nullable=False),
    sa.CheckConstraint('(latitude IS NULL AND longitude IS NULL) OR (latitude IS NOT NULL AND longitude IS NOT NULL)', name='ck_locations_complete_coordinates'),
    sa.CheckConstraint('address IS NULL OR length(trim(address)) BETWEEN 1 AND 500', name='ck_locations_address_length'),
    sa.CheckConstraint('city IS NULL OR length(trim(city)) BETWEEN 1 AND 200', name='ck_locations_city_length'),
    sa.CheckConstraint('country IS NULL OR (length(country) = 2 AND country = upper(country))', name='ck_locations_country_iso_alpha2'),
    sa.CheckConstraint('latitude IS NULL OR latitude BETWEEN -90.0 AND 90.0', name='ck_locations_latitude'),
    sa.CheckConstraint('longitude IS NULL OR longitude BETWEEN -180.0 AND 180.0', name='ck_locations_longitude'),
    sa.CheckConstraint('name IS NOT NULL OR address IS NOT NULL OR latitude IS NOT NULL', name='ck_locations_has_description'),
    sa.CheckConstraint('name IS NULL OR length(trim(name)) BETWEEN 1 AND 200', name='ck_locations_name_length'),
    sa.CheckConstraint('postal_code IS NULL OR length(trim(postal_code)) BETWEEN 1 AND 32', name='ck_locations_postal_code_length'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.create_index('ix_locations_coordinates', ['latitude', 'longitude'], unique=False)
        batch_op.create_index('ix_locations_country_city_postal_code', ['country', 'city', 'postal_code'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.CheckConstraint('length(trim(name)) BETWEEN 1 AND 64', name='ck_users_name_length'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ux_users_name_nocase', [sa.literal_column('lower(name)')], unique=True)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('organizer_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sqlalchemy_types.UTCDateTime(), nullable=True),
    sa.Column('duration_in_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('canceled_at', sqlalchemy_types.UTCDateTime(), nullable=True),
    sa.Column('deletion_scheduled_at', sqlalchemy_types.UTCDateTime(), nullable=True),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.CheckConstraint("(status = 'active' AND canceled_at IS NULL) OR (status = 'canceled' AND canceled_at IS NOT NULL)", name='ck_events_cancellation_state'),
    sa.CheckConstraint("status IN ('active', 'canceled')", name='ck_events_status'),
    sa.CheckConstraint('duration_in_minutes > 0', name='ck_events_positive_duration'),
    sa.CheckConstraint('length(trim(title)) BETWEEN 1 AND 250', name='ck_events_title_length'),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organizer_id'], ['users.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index('ix_events_deletion_scheduled_at', ['deletion_scheduled_at'], unique=False)
        batch_op.create_index('ix_events_location_id', ['location_id'], unique=False)
        batch_op.create_index('ix_events_organizer_id', ['organizer_id'], unique=False)
        batch_op.create_index('ix_events_scheduled_at', ['scheduled_at'], unique=False)
        batch_op.create_index('ix_events_status', ['status'], unique=False)

    op.create_table('joiners',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('joined_at', sqlalchemy_types.UTCDateTime(), nullable=False),
    sa.Column('left_at', sqlalchemy_types.UTCDateTime(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_strict=True
    )
    with op.batch_alter_table('joiners', schema=None) as batch_op:
        batch_op.create_index('ix_joiners_event_id', ['event_id'], unique=False)
        batch_op.create_index('ix_joiners_user_id', ['user_id'], unique=False)
        batch_op.create_index('ux_joiners_active_user_event', ['user_id', 'event_id'], unique=True, sqlite_where=sa.text('left_at IS NULL'), postgresql_where=sa.text('left_at IS NULL'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('joiners', schema=None) as batch_op:
        batch_op.drop_index('ux_joiners_active_user_event', sqlite_where=sa.text('left_at IS NULL'), postgresql_where=sa.text('left_at IS NULL'))
        batch_op.drop_index('ix_joiners_user_id')
        batch_op.drop_index('ix_joiners_event_id')

    op.drop_table('joiners')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_status')
        batch_op.drop_index('ix_events_scheduled_at')
        batch_op.drop_index('ix_events_organizer_id')
        batch_op.drop_index('ix_events_location_id')
        batch_op.drop_index('ix_events_deletion_scheduled_at')

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ux_users_name_nocase')

    op.drop_table('users')
    with op.batch_alter_table('locations', schema=None) as batch_op:
        batch_op.drop_index('ix_locations_country_city_postal_code')
        batch_op.drop_index('ix_locations_coordinates')

    op.drop_table('locations')
    # ### end Alembic commands ###
